// build-info.js — Auto-generated by GitHub Actions on every push to main.
// Do NOT edit manually; changes will be overwritten.
window.BUILD_INFO = {
  sha:     "7f5693a",
  shaFull: "7f5693ace5162aac0b2fd0f1b1ac6a1484195a12",
  message: "fix: rename canvas id to trends-chart-canvas to prevent window.functionalityChart collision\n",
  date:    "2026-06-24T15:40:45-04:00",
  url:     "https://github.com/dennismzanetti/FibroSymptomTracker/commit/7f5693ace5162aac0b2fd0f1b1ac6a1484195a12"
};
