// build-info.js — Auto-generated by GitHub Actions on every push to main.
// Do NOT edit manually; changes will be overwritten.
window.BUILD_INFO = {
  sha:     "c4ebb04",
  shaFull: "c4ebb04182563b674665ace5d60e57876ac1d0c7",
  message: "fix: remove hardcoded height=\"200\" from canvas; Chart.js must size from CSS wrapper\n",
  date:    "2026-06-24T15:25:43-04:00",
  url:     "https://github.com/dennismzanetti/FibroSymptomTracker/commit/c4ebb04182563b674665ace5d60e57876ac1d0c7"
};
