// build-info.js — Auto-generated by GitHub Actions on every push to main.
// Do NOT edit manually; changes will be overwritten.
window.BUILD_INFO = {
  sha:     "cb9948f",
  shaFull: "cb9948f64019a045e05fccff1e9b425d57060f3d",
  message: "Widen notes column to 2fr, keep prescriber at 1fr\n",
  date:    "2026-06-26T14:05:56-04:00",
  url:     "https://github.com/dennismzanetti/FibroSymptomTracker/commit/cb9948f64019a045e05fccff1e9b425d57060f3d"
};
