// build-info.js — Auto-generated by GitHub Actions on every push to main.
// Do NOT edit manually; changes will be overwritten.
window.BUILD_INFO = {
  sha:     "8fc27aa",
  shaFull: "8fc27aac73f7d8318e1bbab38d53d3a428dc0016",
  message: "feat: add sticky anchor navigation to settings tab\n",
  date:    "2026-06-22T13:53:23-04:00",
  url:     "https://github.com/dennismzanetti/FibroSymptomTracker/commit/8fc27aac73f7d8318e1bbab38d53d3a428dc0016"
};
