// build-info.js — Auto-generated by GitHub Actions on every push to main.
// Do NOT edit manually; changes will be overwritten.
window.BUILD_INFO = {
  sha:     "786ba1c",
  shaFull: "786ba1c5068e1883e0119ae7eadf0f7b960562d4",
  message: "fix: fix heredoc indentation bug in build-info.js generation\n",
  date:    "2026-06-22T13:22:33-04:00",
  url:     "https://github.com/dennismzanetti/FibroSymptomTracker/commit/786ba1c5068e1883e0119ae7eadf0f7b960562d4"
};
